### ISSUE TITLE
SvnTag should create parent directories

### ISSUE THREAD

**Issue by thinkingstone** [martoe/gradle-svntools-plugin#22]
I like to create a svn tag based on the scheme "tags/PROJECT/VERSION/MODULE". 

example:
```
task svnTag(type: at.bxm.gradleplugins.svntools.tasks.SvnTag) {
	tagName = "${project.name}/${project.version}/${project.name}"
	commitMessage = "tag ${project.name} version ${project.version}"
}
```

Running this task does not work. The parent directories were not created. 

Stacktrace
```
Caused by: org.gradle.api.InvalidUserDataException: svn-copy failed for /svn/REPO/tags/PROJECT/1.1-SNAPSHOT/MODULE
svn: E160013: Commit failed (details follow):
svn: E160013: '/svn/REPO/tags/PROJECT/1.1-SNAPSHOT' path not found: 404 Not Found (https://PRIVATE)
	at at.bxm.gradleplugins.svntools.internal.SvnCopy.run(SvnCopy.groovy:61)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 70 more
Caused by: org.tmatesoft.svn.core.SVNException: svn: E160013: Commit failed (details follow):
svn: E160013: '/svn/REPO/tags/PROJECT/1.1-SNAPSHOT' path not found: 404 Not Found (https://PRIVATE)
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:64)
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:51)
	at org.tmatesoft.svn.core.internal.wc.SVNCopyDriver.copyReposToRepos(SVNCopyDriver.java:378)
	at org.tmatesoft.svn.core.internal.wc.SVNCopyDriver.setupCopy(SVNCopyDriver.java:627)
	at org.tmatesoft.svn.core.internal.wc16.SVNCopyClient16.doCopy(SVNCopyClient16.java:440)
	at org.tmatesoft.svn.core.internal.wc2.remote.SvnNgReposToReposCopy.run(SvnNgReposToReposCopy.java:65)
	at org.tmatesoft.svn.core.internal.wc2.remote.SvnNgReposToReposCopy.run(SvnNgReposToReposCopy.java:23)
	at org.tmatesoft.svn.core.internal.wc2.SvnOperationRunner.run(SvnOperationRunner.java:20)
	at org.tmatesoft.svn.core.wc2.SvnOperationFactory.run(SvnOperationFactory.java:1149)
	at org.tmatesoft.svn.core.wc2.SvnOperation.run(SvnOperation.java:294)
	at org.tmatesoft.svn.core.wc2.SvnRemoteCopy.run(SvnRemoteCopy.java:227)
	at org.tmatesoft.svn.core.wc.SVNCopyClient.doCopy(SVNCopyClient.java:581)
	at at.bxm.gradleplugins.svntools.internal.SvnCopy.run(SvnCopy.groovy:50)
	... 78 more
```

Please change SvnTag Task to create the parent directories.

Possible changes in SvnCopy.groovy 
```
def copied = clientManager.copyClient.doCopy([copySource] as SVNCopySource[], destUrl, false, true, true, commitMessage, null);
```

**Comment by martoe** [comment]
[v1.5](https://github.com/martoe/gradle-svntools-plugin/releases/tag/v1.5) released
Thanks for reporting!
