### ISSUE TITLE
Support for svn revert and svn patch

### ISSUE THREAD

**Issue by charro** [martoe/gradle-svntools-plugin#30]
In order to make build scripts, would be great to be able to apply automatically SVN patches and also to be able to revert any "dirty" modified code with a SVN revert.

Thanks and cool job here already !

**Comment by martoe** [comment]
About applying patches: what functionality are you thinking of? 
Maybe you can write a fake Gradle script as an example...

**Comment by charro** [comment]
Sure, right now we are doing the same thing (revert and then patch) in our project calling directly the svn executable:

`exec{
    	workingDir libsDir
    	commandLine 'cmd', '/c', svnexecutable, "revert", "--recursive", "--non-interactive", "."
    }`

`exec{
    	workingDir libsDir
    	commandLine 'cmd', '/c', svnexecutable, "patch", "--non-interactive", "svnPatchFile.patch", "."
    }`

So the idea would be to substitute the code above with a call to your plugin, something like:

SvnRevert{
     dir  libsDir
     recursive   true
}

SvnPatch{
     dir  libsDir
     patchFile  svnPatchFile.patch
}

**Comment by martoe** [comment]
@charro a first implementation is available in the develop branch - see the example at https://github.com/martoe/gradle-svntools-plugin/tree/develop/examples/patch
Does this work for you?

**Comment by charro** [comment]
Nice !!
From what I see in your example, it looks exactly as what I was looking for. 
Are you going to upload a new version on the plugin repo so I can try it ?

**Comment by martoe** [comment]
v1.7 released

**Comment by charro** [comment]
Hi again Martoe

First of all, thanks for your work and your support. I just tried version 1.7 of the plugin.

The task SvnRevert worked like a charm, but when I try the SvnApplyPatch, just copying the example you put in documentation I get the following error:

> 12:54:26.724 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :applySvnPatches (Thread[Daemon worker Thread 11,5,main]) started.
12:54:26.724 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :applySvnPatches
12:54:26.724 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':applySvnPatches'
12:54:26.724 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':applySvnPatches' is up-to-date
12:54:26.724 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':applySvnPatches' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
12:54:26.724 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':applySvnPatches'.
12:54:26.725 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':applySvnPatches'
12:54:26.725 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :applySvnPatches FAILED
12:54:26.726 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :applySvnPatches (Thread[Daemon worker Thread 11,5,main]) completed. Took 0.002 secs.
12:54:26.726 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.1 completed (0 in use)
12:54:26.726 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 11,5,main]] finished, busy: 0.002 secs, idle: 0.001 secs
12:54:26.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
12:54:26.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:54:26.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
12:54:26.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
12:54:26.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':applySvnPatches'.
12:54:26.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Neither path nor baseDir may be null or empty string. path='null' basedir='D:\development\onlinesandbox'
12:54:26.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
12:54:26.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
12:54:26.727 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
12:54:26.727 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
12:54:26.727 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
12:54:26.727 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
12:54:26.727 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 1.214 secs


Any idea ?

**Comment by martoe** [comment]
Can you please post your build.gradle and the stacktrace (`-s` option)?

**Comment by charro** [comment]
Sure, here is my script:

 buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "at.bxm.gradleplugins:gradle-svntools-plugin:latest.release"
  }
}

apply plugin: "at.bxm.svntools"

task applySvnPatches(type: at.bxm.gradleplugins.svntools.tasks.SvnApplyPatch) << {
	//println "\nApplying patch to lib to make Android working"
	patchFile = "../../" + configFilesDir + "/AndroidPatch.patch"
  	dir = libsDir + "/android"
}

And the stacktrace:

> * Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':applySvnPatches'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:82)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:49)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:240)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.IllegalArgumentException: Neither path nor baseDir may be null or empty string. path='null' basedir='D:\development\onlinesandbox'
        at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:67)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:80)
        at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:80)
        at org.gradle.api.internal.project.DefaultProject.file(DefaultProject.java:709)
        at org.gradle.api.internal.file.FileOperations$file.call(Unknown Source)
        at at.bxm.gradleplugins.svntools.tasks.SvnApplyPatch.run(SvnApplyPatch.groovy:22)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:133)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:126)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:115)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more


By the way, i'm using Gradle 3.0 in case it has something to do.

**Comment by martoe** [comment]
You are mixing up task configuration and task execution. This should work:
```
task applySvnPatches(type: at.bxm.gradleplugins.svntools.tasks.SvnApplyPatch) {
  patchFile = "../../" + configFilesDir + "/AndroidPatch.patch"
  dir = libsDir + "/android"
}
```
Using "<<" (like you did) executes the closure at runtime, which leads to strange errors...

Regarding Gradle 3.0: I will release plugin v2.0 shortly, which should be 100% compatible to Gradle 3.0 (#34)

**Comment by charro** [comment]
Yep, you are right, that was the problem !

Many thanks for your help. I'm looking forward for the 2.0 version of the plugin.

I'll close the issue now.
